// Generated by https://quicktype.io

export interface IModelFIlterGloblalTablaSolicitudes {
    global:   Estadesc;
    requcodi: Estadesc;
    fechsoli: Estadesc;
    fechfeco: Estadesc;
    estadesc: Estadesc;
    requdeta: Estadesc;
}

export interface Estadesc {
    value:     string;
    matchMode: string;
}
